name: quran_app
description: "A new Flutter project."
publish_to: "none"

version: 1.1.0+2
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  quran: ^1.3.1
  flutter_native_splash: ^2.4.4
  provider: ^6.0.0
  # audioplayers: ^6.1.1
  get_storage: ^2.1.1
  url_launcher: ^6.3.1
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.0.0
  just_audio: ^0.9.44
  google_fonts: ^6.2.1
  flutter_staggered_animations: ^1.1.1
  # assets_audio_player: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image.png"
  min_sdk_android: 21
  adaptive_icon_background: "#075E54"
  adaptive_icon_foreground: "assets/image.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#075E54"
  image: assets/image.png
  android_12:
    image: assets/image.png
    icon_background_color: "#FFFFFF"
  ios: true
  android: true
  web: false
