org.gradle.jvmargs=-Xmx4096M
android.useAndroidX=true
android.enableJetifier=true

# Disable R8 full mode to avoid compilation errors
android.enableR8.fullMode=false

# Gradle timeout settings
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true


MY_STORE_FILE=my-release-key.keystore
MY_KEY_ALIAS=my-key-alias
MY_STORE_PASSWORD=159632
MY_KEY_PASSWORD=159632
